[app]
workers = 1

# TTS provider to use from the [tts.*] options below.
tts_provider = "google"

# Postgres database.
[db]
host = "localhost"
port = 9432
db = "alar"
user = "alar"
password = ""
ssl_mode = "disable"
max_open = 25
max_idle = 25

# Optional DSN params. Eg: a=b&c=d
params = ""


# TTS providers.
[tts.google]
# API key for the TTS provider
api_key = ""

# Language code for the TTS provider. For example, "en-US" for English (US), "kn-IN" for Kannada (India)
language_code = "kn-IN"

# Voice name for the TTS provider. For example, "en-US-Wavenet-D" for Google TTS
voice_name = "kn-IN-Standard-A"

# Output format of the audio file. Options: "mp3", "ogg_opus", "linear16"
output_format = "mp3"

# Directory to save the generated audio files
out_dir = "tts"

# Rate limit
req_per_sec = 10

# Speech rate
speech_rate = 0.85

# Pitch
pitch = 0

# Volume Gain (DB)
volume_gain_db = 0
